server:
  port: 8084

me:
  profile: default


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # ??? ?? ? ? data.sql ??
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true



site:
  link: https://feelpass.cn

--- # local profile
spring.config.activate.on-profile: local
me:
  profile: local

--- # prd profile
spring.config.activate.on-profile: prod
me:
  profile: local


--- # test profile
spring.config.activate.on-profile: test
me:
  profile: test

server:
  port: 8085
